version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: flaskdb
    depends_on:
      - db
    restart: always


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdb
    volumes:
      - db_data:/var/lib/mysql
    restart: always


volumes:
  db_data:
